engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
  phpcodesniffer:
    enabled: true

ratings:
  paths:
  - "**.js"
  - "**.php"
exclude_paths:
  - "app/code/community/Ecocode/Profiler/Tests/"
